tweeza/items/models.py
from extensions import db
from users.models import User
import datetime


class Title(db.EmbeddedDocument):

    title = db.StringField()
    lang = db.StringField(max_length=3)


class Category(db.DynamicDocument):
    """
    Why dynamic document ?
    So we can add other languages fields dynamically (e.g. Tamazight language)
    and add the new translation to all existing categories, see:

    docs.mongoengine.org/guide/defining-documents.html#dynamic-document-schemas

    """

    created_at = db.DateTimeField(default=datetime.datetime.now,
                                  required=True)

    category_id = db.SequenceField(primary_key=True)

    # you can add your name_[lang] at runtime with no worries,
    # it's a Dynamic Document!
    name_ar = db.StringField(max_length=50)
    name_fr = db.StringField(max_length=50)
    name_en = db.StringField(max_length=50)

    description = db.StringField()

    def get_name(self, lang):
        # make this better, latter
        if lang == 'en':
            return self.name_en
        elif lang == 'ar':
            return self.name_ar
        else:
            return self.name_fr


class License(db.DynamicDocument):

    created_at = db.DateTimeField(default=datetime.datetime.now,
                                  required=True)

    license_id = db.SequenceField(primary_key=True)

    name = db.StringField()
    link = db.URLField()

    description = db.StringField()


class Item(db.Document):

    item_id = db.SequenceField(primary_key=True)

    submitted_at = db.DateTimeField(default=datetime.datetime.now,
                                    required=True)

    titles = db.ListField(db.EmbeddedDocumentField(Title),
                          required=True)

    submitter = db.ReferenceField(User)

    category = db.ReferenceField(Category)

    files = db.ListField(db.FileField())

    github = db.URLField()

    blog_post = db.URLField()

    tags = db.ListField(db.StringField(max_length=30))

    description = db.StringField()

    thumbnail = db.ImageField(thumbnail_size=(230, 330, True))

    license = db.ReferenceField(License)

    has_api = db.BooleanField()
    api_url = db.URLField()

    def get_thumbnail(self):
        from flask import url_for
        if self.thumbnail:
            return url_for('items.serve_thumbnail',
                           item_id=self.item_id,
                           filename=self.thumbnail.filename)

        return url_for('static',
                       filename='images/no-thumbnail.png')

    def get_title(self, lang):
        for title in self.titles:
            if title.lang == lang:
                return title.title

        return ''

    meta = {
        'indexes': ['-submitted_at', 'tags'],
        'ordering': ['-submitted_at']
    }

tweeza/items/forms.py
# -*- coding: utf-8 -*-

from flask.ext.wtf import Form
from wtforms import TextField, TextAreaField, SubmitField, SelectField
from wtforms.fields.html5 import URLField
from flask.ext.babel import lazy_gettext as _
from flask_wtf.file import FileField


class BaseForm(Form):
    """
    this contains shared fields among other forms
    """

    blog_post = URLField(_('Blog post URL'))

    ar_title = TextField(_('Item title in Arabic'))
    en_title = TextField(_('Item title in English'))
    fr_title = TextField(_('Item title in French'))

    thumbnail = FileField(_('Thumbnail (minimum dimensions 230x230)'))

    tags = TextField(_('Tags'))

    category = SelectField(_('Category'), choices=[], coerce=int)

    def set_categories(self, categories, lang):
        choices = []
        for category in categories:
            choices.append((category.id, category.get_name(lang)))

        self.category.choices = choices


class AddItemForm(BaseForm):

    github = URLField(_('Remote repository URL'))
    description = TextAreaField(_('Description'))

    files = FileField(_('Files'))

    license = SelectField(_('License'), choices=[], coerce=int)

    submit = SubmitField(_('Add item'))

    def set_licenses(self, licenses):
        choices = []
        for license in licenses:
            choices.append((license.id, license.name))

        self.license.choices = choices


class EditGithubItemForm(BaseForm):

    github = URLField(_('Remote repository URL'))

    submit = SubmitField(_('Update'))


class EditItemForm(BaseForm):

    files = FileField(_('Files'))

    description = TextAreaField(_('Description'))

    license = SelectField(_('License'), choices=[], coerce=int)

    submit = SubmitField(_('Update'))

    def set_licenses(self, licenses):
        choices = []
        for license in licenses:
            choices.append((license.id, license.name))

        self.license.choices = choices

tweeza/frontend/views.py
from flask import (Blueprint, request, redirect, url_for, abort,
                   render_template, flash, current_app as app)
from flask.ext.login import (login_required, login_user, current_user,
                             logout_user)
from users.models import User
from frontend.forms import ContactForm
from flask.ext.babel import gettext as _
from items.models import Item, Category
from flask.ext.mongoengine import Pagination
from flask_mail import Message
from extensions import cache, mail

frontend = Blueprint('frontend', __name__)

github = None  # Global object


@frontend.route("/")
@cache.cached(60)
def index():
    items = Item.objects[:12]
    categories = Category.objects.all()
    return render_template('frontend/index.html', items=items,
                           categories=categories)


@frontend.route("/about/")
@cache.cached(60)
def about():
    return render_template('frontend/about.html')


@frontend.route("/oauth/github")
def oauth_github():
    """Step 1: User Authorization.

    Redirect the user/resource owner to the OAuth provider (i.e. Github)
    using an URL with a few key OAuth parameters.
    """
    from extensions import github_oauth
    global github
    github = github_oauth(app)
    redirect_uri = url_for('frontend.callback',
                           next=request.args.get('next') or
                           request.referrer or None, _external=True)

    params = {'redirect_uri': redirect_uri, 'scope': 'user:email'}
    return redirect(github.get_authorize_url(**params))


# Step 2: User authorization, this happens on the provider.

@frontend.route("/callback")
def callback():
    """ Step 3: Retrieving an access token.

    The user has been redirected back from the provider to your registered
    callback URL. With this redirection comes an authorization code included
    in the redirect URL. We will use that to obtain an access token.
    """

    if not 'code' in request.args:
        flash('You did not authorize the request', category='alert')
        return redirect(url_for('frontend.login'))

    # make a request for the access token credentials using code
    redirect_uri = url_for('frontend.callback', _external=True)

    data = dict(code=request.args['code'],
                redirect_uri=redirect_uri,
                scope='user:email,public_repo')

    auth = github.get_auth_session(data=data)

    # the "me" response
    githuber = auth.get('user').json()
    user = None
    try:
        user = User.objects.get(github_id=githuber['id'])
    except User.DoesNotExist:
        user = None

    if user:
        login_user(user)
        flash(_('Logged in as %s' % user.name), category='success')
        return redirect(url_for('frontend.index'))
    else:
        user = User()

        # mandatory information
        email = ''
        try:
            email = githuber['email']
        except KeyError:
            email = ''

        user.email = email or ''
        location = githuber['location'] if 'location' in githuber else ''
        user.location = location
        name = githuber['login']
        if 'name' in githuber:
            if githuber['name']:
                name = githuber['name']
        user.name = name

        # required information
        user.github_id = githuber['id']
        user.github_username = githuber['login']
        user.oauth_token = auth.access_token

        user.save()

        if login_user(user):
            flash(_("Logged in as %s now get a shiny profile :)" % user.name),
                  category='success')

        return redirect(url_for('users.edit'))


@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        flash(_('Already Logged in as %s' % current_user), category='success')
        return redirect(url_for('frontend.index'))

    return render_template('frontend/login.html')


@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash(_('Logged out'), 'success')
    return redirect(url_for('frontend.index'))


# for anything that have pagination, don't change <param> to something else
# we use this generic name to generate pagination

@frontend.route('/tag/<param>/<int:page>/')
@frontend.route('/tag/<param>/')
@cache.cached(60)
def tag(param, page=1):
    items = Pagination(Item.objects(tags=param), page, 12)
    if len(items.items) == 0:
        return abort(404)
    return render_template('frontend/tag.html', tag=param, items=items)


@frontend.route('/category/<param>/<int:page>/')
@frontend.route('/category/<param>/')
@cache.cached(60)
def category(param, page=1):
    categories = Category.objects.all()
    category = categories.get_or_404(name_en__iexact=param)

    items = Pagination(Item.objects(category=category), page, 12)

    return render_template('frontend/category_listing.html',
                           items=items,
                           current_category=category,
                           categories=categories)


@frontend.route('/user/<int:param>/items/')
@frontend.route('/user/<int:param>/items/<int:page>')
def user_items(param, page=1):
    user = User.objects.get_or_404(user_id=param)
    items = Pagination(Item.objects(submitter=user), page, 12)

    return render_template('frontend/user_items.html',
                           items=items,
                           user=user)


@frontend.route('/contact/', methods=['GET', 'POST'])
def contact():
    form = ContactForm()

    if request.method == 'POST':

        if form.validate_on_submit():

            name = form.name.data.strip()
            email = form.email.data.strip()
            subject = "[dzlibs.io] %s" % form.subject.data.strip()
            message = form.message.data.strip()

            msg = Message(subject, sender=app.config['ADMINS'][0],
                          recipients=app.config['ADMINS'])
            msg.body = """
            From: %s <%s>
            Message:
            %s
            """ % (name, email, message)
            mail.send(msg)

            flash(_('Message sent successfully'), category='success')
            return render_template('frontend/contact.html', form=form)
        else:
            flash(_('Error happened, see below'), category='alert')
            return render_template('frontend/contact.html', form=form)
    else:
        return render_template('frontend/contact.html', form=form)


@frontend.route('/search/')
def search_page():
    query = request.args.get('q')
    if query:
        return redirect(url_for('frontend.search', param=query))
    return render_template('frontend/search_result.html', items=None)


@frontend.route('/search/<param>/<page>')
@frontend.route('/search/<param>')
@cache.cached(60)
def search(param, page=1):
    items = Pagination(Item.objects(titles__title__icontains=param),
                       1, 12)
    return render_template('frontend/search_result.html', items=items)


@frontend.route('/', defaults={'path': ''}, subdomain='api')
def api():
    return url_for('frontend.api')


# just for fun
@frontend.route("/404/")
@cache.cached(3000)
def _404():
    return abort(404)

tweeza/users/views.py
from flask import (Blueprint, render_template, flash, request, redirect,
                   url_for)
from flask.ext.login import login_required, current_user
from users.models import User
from items.models import Item
from users.forms import EditProfileForm
from flask.ext.babel import gettext as _

users = Blueprint('users', __name__, url_prefix='/profile')


@users.route('/')
@login_required
def index():
    items_count = Item.objects(submitter=current_user.id).count()
    return render_template('users/user_profile.html', user=current_user,
                           items_count=items_count)


@users.route('/edit/', methods=['GET', 'POST'])
@login_required
def edit():

    form = EditProfileForm()

    if request.method == 'POST':

        if form.validate_on_submit():
            user = User.objects.get(id=current_user.id)
            user.name = form.name.data.strip()
            user.email = form.email.data.strip()
            user.website = form.website.data.strip()
            user.twitter_username = form.twitter.data.strip('@')
            facebook = form.facebook.data.strip().strip('/').split('/')[-1]
            user.facebook_username = facebook
            user.location = form.location.data.strip()
            user.hireable = bool(form.hireable.data)
            user.bio = form.bio.data.strip()
            user.save()
            flash(_('Profile updated successfully'), category='success')
            return redirect(url_for('users.index'))
        else:
            flash(_('Error happened, see below'), category='alert')
            return render_template('users/edit_profile.html', form=form)
    else:
        form.hireable.default = int(bool(current_user.hireable))
        form.bio.default = current_user.bio or ''
        form.process()

    return render_template('users/edit_profile.html', form=form)


@users.route('/user/<int:id>')
def user_profile(id):
    user = User.objects.get_or_404(user_id=id)
    items_count = Item.objects(submitter=user).count()
    return render_template('users/user_profile.html',
                           user=user,
                           items_count=items_count)

tweeza/templates/items/item_details.html
{% extends 'layouts/base.html' %}

{% set page_title = item.titles | what_title | capitalize %}

{% block body %}
    
    <div class="row">
        <h2>{{ _('Item details') }}</h2>
        <hr>

        <div class="row">
            <div class="small-10 large-8 columns">
                <h3><strong>{{ item.titles | what_title | capitalize }}</strong></h3>

                <ul class="no-bullet inline-list tags">
                    {% for tag in item.tags %}
                        {% if tag %}
                            <li>{% if loop.first %} <strong> {{ _('Tags') }}:</strong> {% endif %}</li>
                            <li><span>
                                <a href="{{ url_for('frontend.tag', param=tag, page=1) }}" class="button tiny secondary"><i class="fi-price-tag"></i> {{ tag }}</a>
                            </span></li>
                        {% endif %}
                    {% endfor %}
                </ul>
                <ul class="no-bullet inline-list">
                    <li><strong>{{ _("Category: ") }}</strong></li>
                    <li>{{ item.category.get_name(g.lang) }}</li>
                </ul>
                <h3 class="subheader">
                {{ _("Item description") }}
                {% if item.github %}
                    {{ _('(pulled from Github)') }}
                {% endif %}
                </h3>
                <article class="panel markdown">
                    {% if item.github %}
                        {{ content | markdown }}
                    {% else %}
                        {% if item.description %}
                            {{ item.description}}
                        {% else %}
                            {{ _("No description yet!") }}
                        {% endif %}
                    {% endif %}
                </article>

                <div id="disqus_thread"></div>
                <script type="text/javascript">
                    var disqus_shortname = 'dzlibs';
                    var disqus_identifier = {{ item.item_id }};

                    (function() {
                        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                    })();
                </script>
                <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>  

            </div>

            <div class="small-4 large-4 columns">
                <div class="row submitter_details">
                    <h3 class="items_details_title"><i class="fi-torso"></i> {{ _('Submitter') }}</h3>
                    <div class="small-9 columns">
                        <ul class="no-bullet">
                            <li><h5><a href="{{ url_for('users.user_profile', id=item.submitter.user_id) }}">{{ item.submitter.name }}</a></h5></li>
                            <li><h5 class="subheader">{{ item.submitted_at | prettify }}</h5></li>
                        </ul>                     
                        <ul class="no-bullet inline-list user-socials">
                            <li><a href="{{ item.submitter.getGithub() }}"><i class="fi-social-github"></i></a></li>
                            {% if item.submitter.twitter_username %}
                                <li><a href="{{ item.submitter.getTwitter() }}"><i class="fi-social-twitter"></i></a></li>
                            {% endif %}

                            {% if item.submitter.facebook_username %}
                                <li><a href="{{ item.submitter.getFacebook() }}"><i class="fi-social-facebook"></i></a></li>
                            {% endif %}

                            {% if item.submitter.website %}
                                <li><a title="{{ _("Submitter website") }}" href="{{ item.submitter.website }}"><i class="fi-link"></i></li>
                            {% endif %}

                        </ul>

                        {% if item.submitter.hireable %}
                            <p class="text-center">
                            <span class="label success radius">{{ _("This guy is free to hire!") }}</span></p>
                        {% endif %}
                    </div>
                    <div class="small-3 columns">
                        <div class="circle">
                            <a href="{{ url_for('users.user_profile', id=item.submitter.user_id) }}">
                                <img src="{{ item.submitter.email | gravatar(size=60) }}">
                            </a>
                        </div>
                    </div>
                </div>
                <ul class="no-bullet">
                    {% if item.blog_post %}
                        <li>
                            <span class="label secondary radius"><strong>{{ _('Heads up!') }}</strong> <a href="{{ item.blog_post}}" target="_blank">{{ _('This item has a blog post!') }}</a></span>
                        </li>
                    {% endif %}

                    {% if item.has_api %}
                        <li>
                            <span class="label secondary radius"><strong>{{ _('Cool!') }}</strong> <a href="{{ item.api_url }}" target="_blank">{{ _('This item has api!') }}</a></span>
                        </li>
                    {% endif %}
                </ul>

                {% if item.github %}
                    <hr>
                    <p class="text-center">
                        <iframe src="http://ghbtns.com/github-btn.html?user={{ user }}&repo={{ repo_name }}&type=watch&count=true&size=large" allowtransparency="true" frameborder="0" scrolling="0" width="120" height="30">
                        </iframe>

                        <iframe src="http://ghbtns.com/github-btn.html?user={{ user }}&repo={{ repo_name }}&type=fork&count=true&size=large" allowtransparency="true" frameborder="0" scrolling="0" width="120" height="30">
                        </iframe>
                    </p>
                    <h3 class="items_details_title"><i class="fi-info"></i> {{ _("Item information") }}:</h3>
                    <ul class="no-bullet">
                        <li><a href="{{ item.github }}" target="_blank" class="button secondary expand"><i class="fi-social-github"></i> {{ _("Item repository on Github") }}</a></li>

                        <h6><strong>{{ _('License') }}:</strong> {{ _("see the license file in the repository or read it in the README file (if it's there!)") }}</h6>

                        <li><strong>{{ _("Clone it: ") }}</strong></li>
                        <li><input type="text" value="{{ clone_string }}" readonly></li>
                        <li><a href="{{ zip_link }}" class="button expand"><i class="fi-download"></i> {{ _("Download") }}</a></li>
                    </ul>
                {% else %}
                    <h5 class="items_details_title">{{ _('License') }}: <a href="{{ item.license.link }}" target="_blank">{{ item.license.name }}</a></h5>
                    <h3 class="items_details_title"><i class="fi-folder"></i> {{ _("Item files") }}:</h3>
                    <hr>
                    <ul class="no-bullet">
                        {% for file in item.files %}
                            <ul class="no-bullet">
                                <li>
                                    <i class="fi-download"></i>
                                    <a href="{{ url_for('items.serve_file', item_id=item.item_id, filename=file.filename) }}">{{ file.filename }}</a>
                                    <span class="label secondary">{{ file.length | filesizeformat }}</span>
                                </li>
                                <li><ul><li><span class="label secondary"><strong>md5:</strong> {{ file.md5 }}</span></li></ul></li>
                            </ul>
                        {% endfor %}
                    </ul>
                {% endif %}
                
                <hr>

                {% if current_user.id == item.submitter.id or current_user.is_admin %}
                    <a href="{{ url_for('items.edit', item_id=item.item_id) }}" class="button expand success">{{ _('Edit item') }}</a>

                    <a href="#" data-reveal-id="deleteItem" data-reveal class="button expand alert">{{ _('Delete item') }}</a>

                    <div id="deleteItem" class="reveal-modal small" data-reveal> 
                        <h2>{{ _('Are you sure you want to delete this item ?')}}</h2> 
                        <p class="lead">{{ _('Oh dear, that was so precious, all files will be lost!') }}</p> 
                        <form action="{{ url_for('items.delete_item', item_id=item.item_id) }}" method="POST">
                            <input class="button expand alert" type="submit" name="submit" value="{{ _('Yes, delete :(') }}"></input>
                        </form>
                        <a class="button secondary expand" onclick="$('#deleteItem').foundation('reveal', 'close');">{{ _("Nah, man! I'm just kidding") }}</a>
                        <a class="close-reveal-modal">&#215;</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock body %}

tweeza/templates/items/items_list.html
{% from "macros/_misc.html" import render_items_listing, render_pagination, render_categories_listing %}

{% extends 'layouts/base.html' %}

{% set page_title = _("Explore items") %}

{% block container %}
	<div class="row">
    	<h2>{{ _('Items list') }}</h2>
    	<hr>

		{{ render_categories_listing(categories, current_category) }}

		{{ render_items_listing(items.items) }}

		{{ render_pagination(items, 'items.paginate') }}
	</div>

{% endblock %}

{% block js_btm %}
    {{ super() }}

    <script src="{{ url_for('static', filename='vendors/underscore/underscore-min.js') }}"></script>
{% endblock %}