tweeza/frontend/views.py
from flask import (Blueprint, request, redirect, url_for, abort,
                   render_template, flash, current_app as app)
from flask.ext.login import (login_required, login_user, current_user,
                             logout_user)
from users.models import User
from frontend.forms import ContactForm
from flask.ext.babel import gettext as _
from items.models import Item, Category
from flask.ext.mongoengine import Pagination
from flask_mail import Message
from extensions import cache, mail

frontend = Blueprint('frontend', __name__)

github = None  # Global object


@frontend.route("/")
@cache.cached(60)
def index():
    items = Item.objects[:12]
    categories = Category.objects.all()
    return render_template('frontend/index.html', items=items,
                           categories=categories)


@frontend.route("/about/")
@cache.cached(60)
def about():
    return render_template('frontend/about.html')


@frontend.route("/oauth/github")
def oauth_github():
    """Step 1: User Authorization.

    Redirect the user/resource owner to the OAuth provider (i.e. Github)
    using an URL with a few key OAuth parameters.
    """
    from extensions import github_oauth
    global github
    github = github_oauth(app)
    redirect_uri = url_for('frontend.callback',
                           next=request.args.get('next') or
                           request.referrer or None, _external=True)

    params = {'redirect_uri': redirect_uri, 'scope': 'user:email'}
    return redirect(github.get_authorize_url(**params))


# Step 2: User authorization, this happens on the provider.

@frontend.route("/callback")
def callback():
    """ Step 3: Retrieving an access token.

    The user has been redirected back from the provider to your registered
    callback URL. With this redirection comes an authorization code included
    in the redirect URL. We will use that to obtain an access token.
    """

    if not 'code' in request.args:
        flash('You did not authorize the request', category='alert')
        return redirect(url_for('frontend.login'))

    # make a request for the access token credentials using code
    redirect_uri = url_for('frontend.callback', _external=True)

    data = dict(code=request.args['code'],
                redirect_uri=redirect_uri,
                scope='user:email,public_repo')

    auth = github.get_auth_session(data=data)

    # the "me" response
    githuber = auth.get('user').json()
    user = None
    try:
        user = User.objects.get(github_id=githuber['id'])
    except User.DoesNotExist:
        user = None

    if user:
        login_user(user)
        flash(_('Logged in as %s' % user.name), category='success')
        return redirect(url_for('frontend.index'))
    else:
        user = User()

        # mandatory information
        email = ''
        try:
            email = githuber['email']
        except KeyError:
            email = ''

        user.email = email or ''
        location = githuber['location'] if 'location' in githuber else ''
        user.location = location
        name = githuber['login']
        if 'name' in githuber:
            if githuber['name']:
                name = githuber['name']
        user.name = name

        # required information
        user.github_id = githuber['id']
        user.github_username = githuber['login']
        user.oauth_token = auth.access_token

        user.save()

        if login_user(user):
            flash(_("Logged in as %s now get a shiny profile :)" % user.name),
                  category='success')

        return redirect(url_for('users.edit'))


@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        flash(_('Already Logged in as %s' % current_user), category='success')
        return redirect(url_for('frontend.index'))

    return render_template('frontend/login.html')


@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash(_('Logged out'), 'success')
    return redirect(url_for('frontend.index'))


# for anything that have pagination, don't change <param> to something else
# we use this generic name to generate pagination

@frontend.route('/tag/<param>/<int:page>/')
@frontend.route('/tag/<param>/')
@cache.cached(60)
def tag(param, page=1):
    items = Pagination(Item.objects(tags=param), page, 12)
    if len(items.items) == 0:
        return abort(404)
    return render_template('frontend/tag.html', tag=param, items=items)


@frontend.route('/category/<param>/<int:page>/')
@frontend.route('/category/<param>/')
@cache.cached(60)
def category(param, page=1):
    categories = Category.objects.all()
    category = categories.get_or_404(name_en__iexact=param)

    items = Pagination(Item.objects(category=category), page, 12)

    return render_template('frontend/category_listing.html',
                           items=items,
                           current_category=category,
                           categories=categories)


@frontend.route('/user/<int:param>/items/')
@frontend.route('/user/<int:param>/items/<int:page>')
def user_items(param, page=1):
    user = User.objects.get_or_404(user_id=param)
    items = Pagination(Item.objects(submitter=user), page, 12)

    return render_template('frontend/user_items.html',
                           items=items,
                           user=user)


@frontend.route('/contact/', methods=['GET', 'POST'])
def contact():
    form = ContactForm()

    if request.method == 'POST':

        if form.validate_on_submit():

            name = form.name.data.strip()
            email = form.email.data.strip()
            subject = "[dzlibs.io] %s" % form.subject.data.strip()
            message = form.message.data.strip()

            msg = Message(subject, sender=app.config['ADMINS'][0],
                          recipients=app.config['ADMINS'])
            msg.body = """
            From: %s <%s>
            Message:
            %s
            """ % (name, email, message)
            mail.send(msg)

            flash(_('Message sent successfully'), category='success')
            return render_template('frontend/contact.html', form=form)
        else:
            flash(_('Error happened, see below'), category='alert')
            return render_template('frontend/contact.html', form=form)
    else:
        return render_template('frontend/contact.html', form=form)


@frontend.route('/search/')
def search_page():
    query = request.args.get('q')
    if query:
        return redirect(url_for('frontend.search', param=query))
    return render_template('frontend/search_result.html', items=None)


@frontend.route('/search/<param>/<page>')
@frontend.route('/search/<param>')
@cache.cached(60)
def search(param, page=1):
    items = Pagination(Item.objects(titles__title__icontains=param),
                       1, 12)
    return render_template('frontend/search_result.html', items=items)


@frontend.route('/', defaults={'path': ''}, subdomain='api')
def api():
    return url_for('frontend.api')


# just for fun
@frontend.route("/404/")
@cache.cached(3000)
def _404():
    return abort(404)

tweeza/templates/layouts/base.html
<!DOCTYPE html>
<html>
    <head class="no-js" lang="{{ g.lang }}"{% if g.lang == 'ar' %} dir="rtl"{% endif %}>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>{% block title %}{{ page_title }}{% endblock %} | {{ _("DzLibs") }}</title>

    <meta name="description" content="{{ _('The Algerian index of reusable resources and librairies') }}">
    <meta name="author" content="Walid ZIOUCHE">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="Shortcut Icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">

    {% block css %}
        {% if g.lang == 'ar' %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/app.rtl.css') }}">
        {% else %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
        {% endif %}
    {% endblock %}

    {% block js_top %}
        <script src="{{ url_for('static', filename='vendors/jquery/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='vendors/foundation/js/vendor/fastclick.js') }}"></script>
    {% endblock %}

    {% block css_style %}
    {% endblock %}

    <!-- IE Fix for HTML5 Tags -->
    <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
    {% include "macros/_ask_user_to_update_ie.html" %}

    {% block topbar %}
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name"><!-- Title Area -->
                <h1>
                    <a href="{{ url_for('frontend.index') }}">DZ <strong>Libs</strong> <small>(beta)</small></a>
                </h1>
                </li>
                <li class="toggle-topbar"><a href="#"><i class="fi-list large"></i></a></li>
            </ul>

            <section class="top-bar-section"><!-- Right Nav Section -->

                <ul class="left">
                    <li><a href="{{ url_for('frontend.contact') }}">{{ _('Contact') }}</a></li>
                    <li><a href="{{ url_for('frontend.about') }}">{{ _('About') }}</a></li>
                    <li class="has-dropdown">
                        <a href="#">{{ _('Language') }}</a>
                        <ul class="dropdown">
                            <li><a href="#" dir="rtl">العربية</a></li>
                            <li><a href="#">Français</a></li>
                        </ul>
                    </li>
                    <li class="has-form">
                        <div class="row collapse">
                            <form method="GET" action="{{ url_for('frontend.search_page') }}">
                                <div class="row collapse">
                                    <div class="small-10 columns">
                                        <input type="search" name='q' value="" placeholder="{{ _('search for an item here...') }}" class="search-input">
                                    </div>
                                    <div class="small-2 columns">
                                        <input type="submit" class="show-for-touch button expand warning" value="{{ _("Go") }}"></input>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </li>
                </ul>
                <ul class="right">
                    <li><a href="{{ url_for('items.index') }}">{{ _('Explore items') }}</a></li>

                    {% if current_user.is_authenticated() %}
                        <li><a href="{{ url_for('items.add') }}">{{ _('Add item') }}</a></li>
                        <li class="has-dropdown">
                            <a href="#"><img src="{{ current_user.email | gravatar }}"> {{ current_user.name }}</a>
                            <ul class="dropdown">
                                <li><a href="{{ url_for('frontend.user_items', param=current_user.user_id) }}"><i class="fi-list-thumbnails"></i> {{ _('My items') }}</a></li>
                                <li><a href="{{ url_for('users.index') }}"><i class="fi-torso"></i> {{ _('Profile') }}</a></li>
                                <li class="active"><a href="{{ url_for('frontend.logout') }}" class=""><i class="fi-arrow-left"></i> {{ _('Logout') }}</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="has-form"><a href="{{ url_for('frontend.login') }}" class="button">{{ _('Register / Sign In') }}</a></li>
                        <li></li>
                    {% endif %}
                </ul>
            </section>
        </nav>

    {% endblock %}

    <div class="wrapper">

        {% block container %}

            {% block flash_message %}
                {% with messages = get_flashed_messages(with_categories=True) %}
                    {% if messages %}
                    <div class="row">
                        {% for category, msg in messages %}
                            <div data-alert class="alert-box {{ category }}">
                                {{ msg }}
                                <a href="#" class="close">&times;</a>
                            </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                {% endwith %}
            {% endblock %}

            {% block body %}
            {% endblock %}
        {% endblock %}

        <div class="push-footer"></div>
    </div>

    <footer>
        <div class="row">
            <div class="medium-4 medium-4 push-8 columns">
                <ul class="home-social inline-list right">
                    <li><a href="https://twitter.com/dzlibs"><i class="fi-social-twitter"></i></a></li>
                    <li><a href="https://www.facebook.com/dzlibs"><i class="fi-social-facebook"></i></a></li>
                    <li><a href="https://github.com/01walid/dzlibs"><i class="fi-social-github"></i></a></li>
                </ul>
            </div>
            <div class="medium-8 medium-8 pull-4 columns">
                <p class="copyright">
                {{ current_year() }} - {{ _("DzLibs project. Under Mozilla Public license v2. Shared items have their OWN licenses. this is a community project. <a href='https://github.com/01walid/dzlibs'>Source code available here</a>.") }}
                </p>
            </div>
        </div>
    </footer>

    {% block js_btm %}
        <script src="{{ url_for('static', filename='vendors/foundation/js/foundation.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/app.js') }}"></script>
    {% endblock %}

</body>
</html>