tweeza/frontend/forms.py
# -*- coding: utf-8 -*-

from flask.ext.wtf import Form, RecaptchaField
from wtforms import TextField, TextAreaField, SubmitField
from wtforms.validators import Required
from flask.ext.wtf.html5 import EmailField
from flask.ext.babel import lazy_gettext as _


class ContactForm(Form):

    name = TextField(_('Name'), validators=[Required()])

    subject = TextField(_('Subject'), validators=[Required()])

    email = EmailField(_('Email'), validators=[Required()],
                       description=_("What's your email address?"))

    message = TextAreaField(_('Message'), validators=[Required()])

    recaptcha = RecaptchaField()

    submit = SubmitField(_('Send'))

tweeza/frontend/views.py
from flask import (Blueprint, request, redirect, url_for, abort,
                   render_template, flash, current_app as app)
from flask.ext.login import (login_required, login_user, current_user,
                             logout_user)
from users.models import User
from frontend.forms import ContactForm
from flask.ext.babel import gettext as _
from items.models import Item, Category
from flask.ext.mongoengine import Pagination
from flask_mail import Message
from extensions import cache, mail

frontend = Blueprint('frontend', __name__)

github = None  # Global object


@frontend.route("/")
@cache.cached(60)
def index():
    items = Item.objects[:12]
    categories = Category.objects.all()
    return render_template('frontend/index.html', items=items,
                           categories=categories)


@frontend.route("/about/")
@cache.cached(60)
def about():
    return render_template('frontend/about.html')


@frontend.route("/oauth/github")
def oauth_github():
    """Step 1: User Authorization.

    Redirect the user/resource owner to the OAuth provider (i.e. Github)
    using an URL with a few key OAuth parameters.
    """
    from extensions import github_oauth
    global github
    github = github_oauth(app)
    redirect_uri = url_for('frontend.callback',
                           next=request.args.get('next') or
                           request.referrer or None, _external=True)

    params = {'redirect_uri': redirect_uri, 'scope': 'user:email'}
    return redirect(github.get_authorize_url(**params))


# Step 2: User authorization, this happens on the provider.

@frontend.route("/callback")
def callback():
    """ Step 3: Retrieving an access token.

    The user has been redirected back from the provider to your registered
    callback URL. With this redirection comes an authorization code included
    in the redirect URL. We will use that to obtain an access token.
    """

    if not 'code' in request.args:
        flash('You did not authorize the request', category='alert')
        return redirect(url_for('frontend.login'))

    # make a request for the access token credentials using code
    redirect_uri = url_for('frontend.callback', _external=True)

    data = dict(code=request.args['code'],
                redirect_uri=redirect_uri,
                scope='user:email,public_repo')

    auth = github.get_auth_session(data=data)

    # the "me" response
    githuber = auth.get('user').json()
    user = None
    try:
        user = User.objects.get(github_id=githuber['id'])
    except User.DoesNotExist:
        user = None

    if user:
        login_user(user)
        flash(_('Logged in as %s' % user.name), category='success')
        return redirect(url_for('frontend.index'))
    else:
        user = User()

        # mandatory information
        email = ''
        try:
            email = githuber['email']
        except KeyError:
            email = ''

        user.email = email or ''
        location = githuber['location'] if 'location' in githuber else ''
        user.location = location
        name = githuber['login']
        if 'name' in githuber:
            if githuber['name']:
                name = githuber['name']
        user.name = name

        # required information
        user.github_id = githuber['id']
        user.github_username = githuber['login']
        user.oauth_token = auth.access_token

        user.save()

        if login_user(user):
            flash(_("Logged in as %s now get a shiny profile :)" % user.name),
                  category='success')

        return redirect(url_for('users.edit'))


@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        flash(_('Already Logged in as %s' % current_user), category='success')
        return redirect(url_for('frontend.index'))

    return render_template('frontend/login.html')


@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash(_('Logged out'), 'success')
    return redirect(url_for('frontend.index'))


# for anything that have pagination, don't change <param> to something else
# we use this generic name to generate pagination

@frontend.route('/tag/<param>/<int:page>/')
@frontend.route('/tag/<param>/')
@cache.cached(60)
def tag(param, page=1):
    items = Pagination(Item.objects(tags=param), page, 12)
    if len(items.items) == 0:
        return abort(404)
    return render_template('frontend/tag.html', tag=param, items=items)


@frontend.route('/category/<param>/<int:page>/')
@frontend.route('/category/<param>/')
@cache.cached(60)
def category(param, page=1):
    categories = Category.objects.all()
    category = categories.get_or_404(name_en__iexact=param)

    items = Pagination(Item.objects(category=category), page, 12)

    return render_template('frontend/category_listing.html',
                           items=items,
                           current_category=category,
                           categories=categories)


@frontend.route('/user/<int:param>/items/')
@frontend.route('/user/<int:param>/items/<int:page>')
def user_items(param, page=1):
    user = User.objects.get_or_404(user_id=param)
    items = Pagination(Item.objects(submitter=user), page, 12)

    return render_template('frontend/user_items.html',
                           items=items,
                           user=user)


@frontend.route('/contact/', methods=['GET', 'POST'])
def contact():
    form = ContactForm()

    if request.method == 'POST':

        if form.validate_on_submit():

            name = form.name.data.strip()
            email = form.email.data.strip()
            subject = "[dzlibs.io] %s" % form.subject.data.strip()
            message = form.message.data.strip()

            msg = Message(subject, sender=app.config['ADMINS'][0],
                          recipients=app.config['ADMINS'])
            msg.body = """
            From: %s <%s>
            Message:
            %s
            """ % (name, email, message)
            mail.send(msg)

            flash(_('Message sent successfully'), category='success')
            return render_template('frontend/contact.html', form=form)
        else:
            flash(_('Error happened, see below'), category='alert')
            return render_template('frontend/contact.html', form=form)
    else:
        return render_template('frontend/contact.html', form=form)


@frontend.route('/search/')
def search_page():
    query = request.args.get('q')
    if query:
        return redirect(url_for('frontend.search', param=query))
    return render_template('frontend/search_result.html', items=None)


@frontend.route('/search/<param>/<page>')
@frontend.route('/search/<param>')
@cache.cached(60)
def search(param, page=1):
    items = Pagination(Item.objects(titles__title__icontains=param),
                       1, 12)
    return render_template('frontend/search_result.html', items=items)


@frontend.route('/', defaults={'path': ''}, subdomain='api')
def api():
    return url_for('frontend.api')


# just for fun
@frontend.route("/404/")
@cache.cached(3000)
def _404():
    return abort(404)

tweeza/templates/frontend/about.html
{% from "macros/_form.html" import render_form %}

{% set page_title = _("About") %}

{% extends "layouts/base.html" %}

{% block body %}

<div class="row">
    <h1>{{ _('About DzLibs project') }}</h1>
    <p>A community-driven Algerian index of reusable assets and libraries. A web app and a set of RESTful APIs to provide a platform for Algerian developers and designers to share reusable resources (Classes, Libraries, Vector files..etc) and easily access them.</p>
    <h3>For instance:</h3>
    <p>You can share/find the XML or JSON of the 48 Algerian Wilayas instead of recreating it every time you need it for your next awesome web/mobile/desktop app. the same goes for the database of the Train/Bus timetable of your city, the Algeria SVG map, the Vector file of <a href="http://en.wikipedia.org/wiki/Maqam_Echahid">Maqam Echahid</a>, and countless other examples, these are *reusable* items we can share for the public good, from developers/designers to developers/designers, for a better Algeria.</p>

    <h3>The APIs part is mostly for developers, it consists of :</h3>

    <p>
        <ul>
            <li>Making <strong>some</strong> of these assets accessible via http(s) requests, for instance: a mobile developer (especially now that we've got the 3G network) could make a GET to <code>api.dzlibs.io/wilayas/23</code> that returns the name of the Wilaya and other on-demand information (e.g. its prayer times).</li>

            <li>pushing for a kind of <strong>standardized</strong> ways to share public data among Algerian developers and different DZ organizations.</li>
        </ul>
    </p>

    <p>These are <strong>just examples</strong>, what we can do and share is countless. we just need to unit, and do the same as our ancestors did, the <strong>Tweeza</strong> of the Algerian web. boosting the IT industry is our shared duty, and for that we need to <strong>share</strong> and think of ourselves as contributors rather than as competitors.</p>
    <h1>Credits</h1>
    <ul>
        <li><a href="https://twitter.com/webdevdz">@webdevdz</a> for the sub-header background image.</li>
        <li><a href="https://twitter.com/djug">@djug</a>, <a href="https://twitter.com/assem_ch">@assem_ch</a>, <a href="https://twitter.com/zendyani">@zendyani</a>, <a href="https://twitter.com/shel3over">@sh3lover</a>, <a href="https://twitter.com/reddines">@reddines</a> and <a href="https://twitter.com/hteghri">@hteghri</a> for their support &amp; early feedbacks.</li>
        <li>The <a href="https://www.facebook.com/groups/dzgeekhangout/">Dz Geek Hangouts</a> crew for supporting the idea.</li>
        <li>All the community out there sharing their items.</li>
    </ul>
</div>
{% endblock %}

tweeza/templates/frontend/category_listing.html
{% from "macros/_misc.html" import render_pagination, render_categories_listing, render_items_listing %}
{% extends 'layouts/base.html' %}

{% set page_title = _("Categories") %}

{% block container %}
    <div class="push"></div>
    {{ render_categories_listing(categories, current_category) }}
    <div class="row">
        {% if not items.items %}
            <h1 class="subheader">{{ _('No items shared in this category, yet.')}}</h1>
        {% else %}
            {{ render_items_listing(items.items) }}
            {{ render_pagination(items, 'frontend.category', current_category.name_en) }}
        {%endif%}
    </div>
    
{% endblock %}

{% block js_btm %}
    {{ super() }}
    <script src="{{ url_for('static', filename='vendors/underscore/underscore-min.js') }}"></script>
{% endblock %}

tweeza/templates/frontend/contact.html
{% extends 'layouts/base.html' %}

{% set page_title = _("Contact us") %}

{% block body %}

<div class="row">
    <h1>{{ page_title }}</h1>
    <hr>

    <p><span class="label secondary"><strong><i class="fi-info"></i> {{ _('Note')}}:</strong> {{ _("For bug reports / feature requests, please open up a <a href='https://github.com/01walid/dzlibs/issues/new'>new issue</a> on github instead.") }}</span></p>


    <form method="POST" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="row">
            <div class="small-2 columns">
                <h3><i class="fi-torso"></i> {{ form.name.label(class_="right inline") }}</h3>
            </div>
            <div class="small-8 columns left">
                {{ form.name(value=current_user.name) }}

                {% if form.name.errors -%}
                    {% for error in form.name.errors -%}
                        <span class="help-block error">{{ error }}</span>
                    {%- endfor %}
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="small-2 columns">
                <h3><i class="fi-mail"></i> {{ form.email.label(class_="right inline") }}</h3>
            </div>
            <div class="small-8 columns left">
                {{ form.email(value=current_user.email or '', placeholder=_("To get back to you")) }}

                {% if form.email.errors -%}
                    {% for error in form.email.errors -%}
                        <span class="help-block error">{{ error }}</span>
                    {%- endfor %}
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="small-2 columns">
                <h3><i class="fi-page-filled"></i> {{ form.subject.label(class_="right inline") }}</h3>
            </div>
            <div class="small-8 columns left">
                {{ form.subject() }}

                {% if form.subject.errors -%}
                    {% for error in form.subject.errors -%}
                        <span class="help-block error">{{ error }}</span>
                    {%- endfor %}
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="small-2 columns">
                <h3><i class="fi-page-edit"></i> {{ form.message.label(class_="right inline") }}</h3>
            </div>
            <div class="small-8 columns left">
                {{ form.message }}

                {% if form.message.errors -%}
                    {% for error in form.message.errors -%}
                        <span class="help-block error">{{ error }}</span>
                    {%- endfor %}
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="small-2 columns">
                <h3>
                    <i class="fi-info"></i>
                    <label class="right inline" for="recaptcha">{{ _('Are you human?') }}</label>
                </h3>
            </div>
            <div class="small-8 columns left">
                {{ form.recaptcha }}

                {% if form.recaptcha.errors -%}
                    {% for error in form.recaptcha.errors -%}
                        <span class="help-block error">{{ error }}</span>
                    {%- endfor %}
                {% endif %}
            </div>
        </div>
        
        <hr>
        
        {{ form.submit(class_="button expand") }}
    </form>
</div>
{% endblock %}

tweeza/templates/frontend/create_profile.html
{% from "macros/_form.html" import render_form %}

{% set page_title = "Create Profile" %}

{% extends "layouts/base.html" %}

{% block body %}

<div class="row">
	<h1>{{ _("One more step, and you're done!") }}</h1>
	<h2>Create Profile <small>Already have an account? <a href="{{ url_for('frontend.login') }}">Sign in</a>, please.</small></h2>
	<h3>{{ session['email'] }}</h3>
	<h3>{{ session['github_id'] }}</h3>
	<h3>{{ session['name'] }}</h3>
	<h3>{{ session['location'] }}</h3>
	<h3>{{ session['oauth_token'] }}</h3>
	<h3>{{ session['github_username'] }}</h3>
	{{ render_form(url_for('frontend.create_profile'), form) }}
</div>

{% endblock %}

tweeza/templates/frontend/index.html
{% from "macros/_misc.html" import render_categories_listing, render_items_listing %}
{% extends 'layouts/base.html' %}

{% set page_title = _("Home") %}

{% block container %}

<div class="container short-header text-center">
  <div class="row headline-down">
    <div class="seven columns">
      <div class="main-headline">
        <div class="push"></div>
        <img src="{{ url_for('static', filename='images/dzlibs-small.png') }}">
        <h2 class="logo-typography"><a href="{{ url_for('frontend.index') }}">Dz Libs</a></h2>
        <h4 class="slogan subheader">{{ _("The Algerian index of reusable assets and libraries") }}</h4>

        <p>{{ _('That is made  of two parts') }}:</p>
        <div class="show-for-small clear"></div>
      </div>

      <div class="row">
        <p class="text-center">
            <a href="http://docs.dzlibsapi.apiary.io/" class="button secondary white">{{ _("api") }}</a>
            &nbsp;&nbsp;&nbsp;&nbsp;{{ _('&amp;') }}&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="#" data-reveal-id="tweezaModal" class="button secondary white" data-reveal>{{ _("tweeza") }}</a>
        </p>
      </div>
    </div>
  </div>
</div>

    {{ render_categories_listing(categories) }}

    {% block flash_message %}
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
            <div class="row">
                {% for category, msg in messages %}
                    <div data-alert class="alert-box {{ category }}">
                        {{ msg }}
                        <a href="#" class="close">&times;</a>
                    </div>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}
    {% endblock %}

    {{ render_items_listing(items) }}


    <div class="row">
        <a href="{{ url_for('items.paginate', page=1) }}" class="button secondary expand">{{ _('Explore more') }}</a>
    </div>


    <div id="tweezaModal" class="reveal-modal small" data-reveal>
        <h4>{{ _("Well, you're already in the <strong>Tweeza</strong> part :)") }}</h4>
        <p class="lead">{{ _("So, let's define sharing items here, as <code>tweezing</code>, the remarkable Algerian tradition our ancestors did <i class='fi-heart'></i> So why not, we, developers/designers, do the same? online!") }}</p> 
        <p>{{ _("Confused? you may check the") }} <a href="{{ url_for('frontend.about') }}">{{ _('about page') }}</a> {{ _("then...") }}</p>
        <a class="close-reveal-modal">&#215;</a>
        <a class="button secondary expand" onclick="$('#tweezaModal').foundation('reveal', 'close');">{{ _("Cool!") }}</a>
    </div>


{% endblock %}

{% block js_btm %}
    {{ super() }}
    <script src="{{ url_for('static', filename='vendors/underscore/underscore-min.js') }}"></script>
{% endblock %}

tweeza/templates/frontend/login.html
{% from "macros/_form.html" import render_form %}

{% set page_title = _("Sign in") %}

{% extends "layouts/base.html" %}

{% block body %}

<div class="row">

    <div class="push"></div>

    <div class="row text-center">
        <h1 class="subheader">{{ _('Login with github') }}</h1>
        <h2>
            <a href="{{ url_for('frontend.oauth_github') }}" class="button secondary large">
            <i class="fi-social-github large"></i>
                {{ _("Sign in/up with Github") }}
            </a>
        </h2>
        <h2 class="subheader">Other Logging options</h2>
        <h5 class="subheader">Other Logging options will -maybe- available later.</h5>
        <h5 class="subheader">However, we highly recommend logging with Github, as we wont be storing any password of yours and is developer-oriented.</h5>
        <h5 class="subheader">if you do not have a Github account, you can register for a new one <a href="https://github.com/join">here</a>.</h5>
    </div>


</div>
{% endblock %}

tweeza/templates/frontend/reauth.html
{% from "macros/_form.html" import render_form %}

{% set page_title = "Reauthenticate" %}

{% extends "layouts/base.html" %}

{% block body %}
<h2>Reauthenticate</h2>
{{ render_form(url_for('frontend.reauth'), form)}}
{% endblock %}

tweeza/templates/frontend/search_result.html
{% from "macros/_misc.html" import render_items_listing, render_pagination %}

{% extends 'layouts/base.html' %}

{% set page_title = _("Search") %}

{% block container %}
    <div class="row">
        <h2>{{ _('Search result') }}</h2>
        <hr>
        
        {% if not items.items %}
            <h1 class="subheader">{{ _('No results :(')}}</h1>
        {% else %}
            {{ render_items_listing(items.items) }}
            {{ render_pagination(items, 'items.paginate') }}
        {%endif%}
    </div>

{% endblock %}

{% block js_btm %}
    {{ super() }}

    <script src="{{ url_for('static', filename='vendors/underscore/underscore-min.js') }}"></script>
{% endblock %}

tweeza/templates/frontend/tag.html
{% from "macros/_misc.html" import render_pagination, render_items_listing %}

{% extends 'layouts/base.html' %}

{% set page_title = _("Tag") %}

{% block container %}
    <div class="row">
        <h2>{{ _('Items tagged with') }}: {{ tag }}</h2>
        <hr>

        {{ render_items_listing(items.items) }}

    </div>

    {{ render_pagination(items, 'frontend.tag', tag) }}

{% endblock %}

{% block js_btm %}
    {{ super() }}

    <script src="{{ url_for('static', filename='vendors/underscore/underscore-min.js') }}"></script>
{% endblock %}

tweeza/templates/frontend/user_items.html
{% from "macros/_misc.html" import render_pagination, render_items_listing %}

{% extends 'layouts/base.html' %}

{% set page_title = _("User items") %}

{% block container %}
    <div class="row">
        <h2>{{ _('Items shared by') }}: {{ user.name }}</h2>
        <hr>

        {% if not items.items %}
            <h1 class="subheader">{{ _('No items shared, yet.')}}</h1>
        {% else %}
            {{ render_items_listing(items.items) }}
            {{ render_pagination(items, 'frontend.user_items', user.user_id) }}
        {%endif%}

           

    </div>

{% endblock %}

{% block js_btm %}
    {{ super() }}

    <script src="{{ url_for('static', filename='vendors/underscore/underscore-min.js') }}"></script>
{% endblock %}