tweeza/frontend/views.py
from flask import (Blueprint, request, redirect, url_for, abort,
                   render_template, flash, current_app as app)
from flask.ext.login import (login_required, login_user, current_user,
                             logout_user)
from users.models import User
from frontend.forms import ContactForm
from flask.ext.babel import gettext as _
from items.models import Item, Category
from flask.ext.mongoengine import Pagination
from flask_mail import Message
from extensions import cache, mail

frontend = Blueprint('frontend', __name__)

github = None  # Global object


@frontend.route("/")
@cache.cached(60)
def index():
    items = Item.objects[:12]
    categories = Category.objects.all()
    return render_template('frontend/index.html', items=items,
                           categories=categories)


@frontend.route("/about/")
@cache.cached(60)
def about():
    return render_template('frontend/about.html')


@frontend.route("/oauth/github")
def oauth_github():
    """Step 1: User Authorization.

    Redirect the user/resource owner to the OAuth provider (i.e. Github)
    using an URL with a few key OAuth parameters.
    """
    from extensions import github_oauth
    global github
    github = github_oauth(app)
    redirect_uri = url_for('frontend.callback',
                           next=request.args.get('next') or
                           request.referrer or None, _external=True)

    params = {'redirect_uri': redirect_uri, 'scope': 'user:email'}
    return redirect(github.get_authorize_url(**params))


# Step 2: User authorization, this happens on the provider.

@frontend.route("/callback")
def callback():
    """ Step 3: Retrieving an access token.

    The user has been redirected back from the provider to your registered
    callback URL. With this redirection comes an authorization code included
    in the redirect URL. We will use that to obtain an access token.
    """

    if not 'code' in request.args:
        flash('You did not authorize the request', category='alert')
        return redirect(url_for('frontend.login'))

    # make a request for the access token credentials using code
    redirect_uri = url_for('frontend.callback', _external=True)

    data = dict(code=request.args['code'],
                redirect_uri=redirect_uri,
                scope='user:email,public_repo')

    auth = github.get_auth_session(data=data)

    # the "me" response
    githuber = auth.get('user').json()
    user = None
    try:
        user = User.objects.get(github_id=githuber['id'])
    except User.DoesNotExist:
        user = None

    if user:
        login_user(user)
        flash(_('Logged in as %s' % user.name), category='success')
        return redirect(url_for('frontend.index'))
    else:
        user = User()

        # mandatory information
        email = ''
        try:
            email = githuber['email']
        except KeyError:
            email = ''

        user.email = email or ''
        location = githuber['location'] if 'location' in githuber else ''
        user.location = location
        name = githuber['login']
        if 'name' in githuber:
            if githuber['name']:
                name = githuber['name']
        user.name = name

        # required information
        user.github_id = githuber['id']
        user.github_username = githuber['login']
        user.oauth_token = auth.access_token

        user.save()

        if login_user(user):
            flash(_("Logged in as %s now get a shiny profile :)" % user.name),
                  category='success')

        return redirect(url_for('users.edit'))


@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        flash(_('Already Logged in as %s' % current_user), category='success')
        return redirect(url_for('frontend.index'))

    return render_template('frontend/login.html')


@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash(_('Logged out'), 'success')
    return redirect(url_for('frontend.index'))


# for anything that have pagination, don't change <param> to something else
# we use this generic name to generate pagination

@frontend.route('/tag/<param>/<int:page>/')
@frontend.route('/tag/<param>/')
@cache.cached(60)
def tag(param, page=1):
    items = Pagination(Item.objects(tags=param), page, 12)
    if len(items.items) == 0:
        return abort(404)
    return render_template('frontend/tag.html', tag=param, items=items)


@frontend.route('/category/<param>/<int:page>/')
@frontend.route('/category/<param>/')
@cache.cached(60)
def category(param, page=1):
    categories = Category.objects.all()
    category = categories.get_or_404(name_en__iexact=param)

    items = Pagination(Item.objects(category=category), page, 12)

    return render_template('frontend/category_listing.html',
                           items=items,
                           current_category=category,
                           categories=categories)


@frontend.route('/user/<int:param>/items/')
@frontend.route('/user/<int:param>/items/<int:page>')
def user_items(param, page=1):
    user = User.objects.get_or_404(user_id=param)
    items = Pagination(Item.objects(submitter=user), page, 12)

    return render_template('frontend/user_items.html',
                           items=items,
                           user=user)


@frontend.route('/contact/', methods=['GET', 'POST'])
def contact():
    form = ContactForm()

    if request.method == 'POST':

        if form.validate_on_submit():

            name = form.name.data.strip()
            email = form.email.data.strip()
            subject = "[dzlibs.io] %s" % form.subject.data.strip()
            message = form.message.data.strip()

            msg = Message(subject, sender=app.config['ADMINS'][0],
                          recipients=app.config['ADMINS'])
            msg.body = """
            From: %s <%s>
            Message:
            %s
            """ % (name, email, message)
            mail.send(msg)

            flash(_('Message sent successfully'), category='success')
            return render_template('frontend/contact.html', form=form)
        else:
            flash(_('Error happened, see below'), category='alert')
            return render_template('frontend/contact.html', form=form)
    else:
        return render_template('frontend/contact.html', form=form)


@frontend.route('/search/')
def search_page():
    query = request.args.get('q')
    if query:
        return redirect(url_for('frontend.search', param=query))
    return render_template('frontend/search_result.html', items=None)


@frontend.route('/search/<param>/<page>')
@frontend.route('/search/<param>')
@cache.cached(60)
def search(param, page=1):
    items = Pagination(Item.objects(titles__title__icontains=param),
                       1, 12)
    return render_template('frontend/search_result.html', items=items)


@frontend.route('/', defaults={'path': ''}, subdomain='api')
def api():
    return url_for('frontend.api')


# just for fun
@frontend.route("/404/")
@cache.cached(3000)
def _404():
    return abort(404)

tweeza/users/views.py
from flask import (Blueprint, render_template, flash, request, redirect,
                   url_for)
from flask.ext.login import login_required, current_user
from users.models import User
from items.models import Item
from users.forms import EditProfileForm
from flask.ext.babel import gettext as _

users = Blueprint('users', __name__, url_prefix='/profile')


@users.route('/')
@login_required
def index():
    items_count = Item.objects(submitter=current_user.id).count()
    return render_template('users/user_profile.html', user=current_user,
                           items_count=items_count)


@users.route('/edit/', methods=['GET', 'POST'])
@login_required
def edit():

    form = EditProfileForm()

    if request.method == 'POST':

        if form.validate_on_submit():
            user = User.objects.get(id=current_user.id)
            user.name = form.name.data.strip()
            user.email = form.email.data.strip()
            user.website = form.website.data.strip()
            user.twitter_username = form.twitter.data.strip('@')
            facebook = form.facebook.data.strip().strip('/').split('/')[-1]
            user.facebook_username = facebook
            user.location = form.location.data.strip()
            user.hireable = bool(form.hireable.data)
            user.bio = form.bio.data.strip()
            user.save()
            flash(_('Profile updated successfully'), category='success')
            return redirect(url_for('users.index'))
        else:
            flash(_('Error happened, see below'), category='alert')
            return render_template('users/edit_profile.html', form=form)
    else:
        form.hireable.default = int(bool(current_user.hireable))
        form.bio.default = current_user.bio or ''
        form.process()

    return render_template('users/edit_profile.html', form=form)


@users.route('/user/<int:id>')
def user_profile(id):
    user = User.objects.get_or_404(user_id=id)
    items_count = Item.objects(submitter=user).count()
    return render_template('users/user_profile.html',
                           user=user,
                           items_count=items_count)

tweeza/templates/macros/_ask_user_to_update_ie.html
<!--[if lt IE 7]>
    <p class="chromeframe">
        {{ _('You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.') }}
    </p>
<![endif]-->

tweeza/templates/macros/_form.html
{% macro render_checkbox(field) %}
<div class="control-group{% if field.errors %} error{% endif %}">
    <div class="controls">
        <label for="{{ field.id }}" class="checkbox inline">
            {{ field }} {{ field.label.text }}
        </label>
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
            {% for error in field.errors -%}
            <span class="help-block error">{{ error|e }}</span>
            {%- endfor %}
        {%- endif %}
    </div>
</div>
{% endmacro%}

{% macro render_radio(field) %}
<div class="control-group{% if field.errors %} error{% endif %}">
    {{ field.label(class_="control-label") }}
    <div class="controls">
        {% for subfield in field -%}
        <label for="{{ subfield.id }}" class="radio inline">
            {{ subfield }} {{ subfield.label.text }}
        </label>
        {%- endfor %}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
            {% for error in field.errors -%}
            <span class="help-block error">{{ error }}</span>
            {%- endfor %}
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_datepicker(field) %}
<div class="control-group{% if field.errors %} error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="controls">
        {{ field() }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
            {% for error in field.errors -%}
            <span class="help-block error">{{ error }}</span>
            {%- endfor %}
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_textarea(field) %}
<div class="control-group{% if field.errors %} error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="controls">
        {{ field(class="span6", rows="5") }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
            {% for error in field.errors -%}
            <span class="help-block error">{{ error }}</span>
            {%- endfor %}
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_input(field) %}
<div class="control-group{% if field.errors %} error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="controls">
        {{ field }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
            {% for error in field.errors -%}
            <span class="help-block error">{{ error }}</span>
            {%- endfor %}
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_action(field) %}
<div class="control-group">
    <div class="form-actions">
        {{ field(class_="button") }}
    </div>
</div>
{% endmacro %}

{% macro render_form(url, form, horizontal=False, legend=None, confirm_msg=None, formid=None) %}
{% set idattr = "id=" + formid if formid else "" %}
<form {{idattr}} class="{% if horizontal %}form-horizontal{% endif %}" method="POST" action="{{ url }}"
    {% if confirm_msg %}onsubmit='return confirm("{{ confirm_msg }}");' {% endif %} 
    {% if form.multipart %}enctype="multipart/form-data"{% endif %} >
    {{ form.hidden_tag() }}
    <fieldset>
        {% if legend %}
        <legend>{{ legend|safe }}</legend>
        {% endif %}
        {% set focus = True %}
        {% for field in form %}
            {% if field.type != "HiddenField" and field.type != "CSRFTokenField" %}
                {% if field.type == "RadioField" %}
                    {{ render_radio(field) }}
                {% elif field.type == "BooleanField" %}
                    {{ render_checkbox(field) }}
                {% elif field.type == "SubmitField" %}
                    {{ render_action(field) }}
                {% elif field.type == "TextAreaField" %}
                    {{ render_textarea(field) }}
                {% elif field.type == "DateField" %}
                    {{ render_datepicker(field) }}
                {% elif field.type == "TextField" %}
                    {% if focus %}
                        {{ render_input(field) }}
                        {% set focus = False %}
                    {% else %}
                        {{ render_input(field) }}
                    {% endif %}
                {% else %}
                    {{ render_input(field) }}
                {% endif %}
            {% endif %}
        {% endfor %}
    </fieldset>
</form>
{% endmacro %}

tweeza/templates/macros/_misc.html
{% macro render_items_listing(items) %}
    <div class="row grid">
        {% for item in items %}
        <div class="item">
                <div class="item-info" style="background-image: url({{ item.get_thumbnail() }});">
                <a href="{{ url_for('items.detail', item_id=item.item_id) }}">
                <hgroup>
                    <h5>{{ item.titles | what_title}}</h5>
                    <h6 class="subheader">{{ item.submitted_at | prettify }} <em>{{_("in") }} </em>{{ item.category.name_en }}</h6>
                </hgroup>
                </a>
            </div>
            <a class="submitter" href="{{ url_for('users.user_profile', id=item.submitter.user_id) }}">
                <img src="{{ item.submitter.email | gravatar(size=30) }}"> {{ item.submitter.getName() | truncate(23) }}
            </a>
        </div>
        {% endfor %}
    </div>

{% endmacro %}


{% macro render_categories_listing(categories, current_category=None) %}
    <div class="row">
        <dl class="sub-nav small-12 columns">
            <dt>{{ _('CATEGORY') }}:</dt>
                <dd class="{% if not current_category %}active{% endif %}"><a href="{{ url_for('items.index') }}">{{ _('All') }}</a></dd>
                {% for category in categories %}
                    <dd class='{{ "active" if category == current_category }}'><a href="{{ url_for('frontend.category', param=category.name_en)}}">{{ category.get_name(g.lang) }}</a></dd>
                {% endfor %}
        </dl>
    </div>
{% endmacro %}

{% macro render_pagination(pagination, endpoint, what=None) %}

    {% if pagination.pages > 1 %}
        <div class="row">
            <div class="pagination-centered">
                <ul class="pagination">
                    {% if pagination.has_prev %}
                        <li class="{% if not pagination.has_prev %}arrow unavailable{% endif %}"><a href="{{ url_for(endpoint, param=what, page=pagination.page-1) }}">&laquo;</a></li>
                    {% else %}
                        <li class="arrow unavailable"><a href="">&laquo;</a></li>
                    {% endif %}

                    {% for page in pagination.iter_pages() %}
                        {% if page %}
                            <li class='{% if page == pagination.page %}current{% endif %}'>
                                <a href='{{ url_for(endpoint, param=what, page=page) }}'>{{ page }}</a>
                            </li>
                        {% else %}
                            <li class="unavailable"><a href="">&hellip;</a></li></li>
                        {% endif %}
                    {% endfor %}
                    {% if pagination.has_next %}
                        <li class="next {% if not pagination.has_next %}arrow{% endif %}"><a href="{{ url_for(endpoint, param=what, page=pagination.page+1) }}">&raquo;</a></li>
                    {% else %}
                        <li class="arrow unavailable"><a href="">&raquo;</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    {% endif %}
{% endmacro %}

tweeza/templates/macros/_reset_password.html
<p>Forgot your password, {{ username }}?</p>

<p>{{ project }} received a request to reset the password for your {{ project }} account {{ username }}.</p>

<p>If you want to reset your password, click on the link below (or copy and paste the URL into your browser):</p>

<a href="{{ url }}">Click to Reset Password</a>

<p>This link takes you to a secure page where you can change your password. For tips on selecting a strong password, see our Safe Tweeting help page.</p>

<p>If you don't want to reset your password, please ignore this message. Your password will not be reset. If you have any concerns, please contact us at {{ project }} Support.</p>

<p>The {{ project }} Team</p>